# 服务器端口配置
server:
  port: 8080

# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easynotes?useSSL=false&serverTimezone=Asia/Tokyo
    username: root
    password: 1234

# 日志记录配置
logging:
  level:
    com.lrs.mapper: debug
